#ifndef ERRORS_H
#include <fenv.h>

enum CVectorCode {
  CVECTOR_SUCCESS = 0,
  CVECTOR_ZERO_DIVISON_ERROR = 1,
  CVECTOR_OVERFLOW_ERROR = 2,
  CVECTOR_UNDERFLOW_ERROR = 3,
  CVECTOR_INEXACT_VALUE = 4,
  CVECTOR_INVALID_ERROR = 5,
  CVECTOR_FPE_UNSUPPORTED = 6
};

int GetErrorCode();

#define ERRORS_H
#endif
